name: 编译 OpenWrt 25.12.2 x86_64 2GB空间

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 下载源码 25.12.2
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v25.12.2

      - name: 更新插件
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 写入配置 x86_64 + 2GB分区
        run: |
          cat > .config << EOF
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
CONFIG_TARGET_ROOTFS_PARTSIZE=2048
CONFIG_TARGET_KERNEL_PARTSIZE=32
EOF
          make defconfig

      - name: 开始编译
        run: make -j4

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-x86-64-25.12.2-2GB
          path: bin/targets/x86/64/*.img.gz
